# Generated by Django 2.2.3 on 2019-08-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0002_auto_20190815_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='costo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
