# Generated by Django 2.2.4 on 2019-08-17 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0003_auto_20190815_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='fecha_inscripcion',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='participante',
            name='fecha_pago',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
