# Generated by Django 2.2.4 on 2019-08-17 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_registro', '0004_auto_20190817_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participante',
            name='costo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
