# Generated by Django 2.2.3 on 2019-08-15 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='descripcion',
            field=models.CharField(choices=[('registrador', 'Registrador'), ('regalo', 'Regalo')], max_length=15),
        ),
    ]
